/*
 * PASSLOCK (version 1.0) - A Simple Password Manager APP 
 *
 * @author Nuno Spencer
 *
 * www.nunospencer.com
 * www.nunospencer.com/passlockv1
 */

import java.awt.event.KeyEvent;
import java.util.Random;
import javax.swing.JOptionPane;

public class RANDOMIZE_dialogBox_v1 extends javax.swing.JDialog {
    public static RandomOuptDialog outputdialog;                                //object of child dialog, used in method CreateOutDialog(String psw) - defined below          
    
    public RANDOMIZE_dialogBox_v1(java.awt.Frame parent, boolean modal)         //constructor for parent dialog
    {
        super(parent, modal);
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        randomizeOptsButtonGroup = new javax.swing.ButtonGroup();
        randomizePassLenghtLabel_v1 = new javax.swing.JLabel();
        randomizePassLenghtTextField_v1 = new javax.swing.JTextField();
        randomizeCancelBtn = new javax.swing.JButton();
        randomizeGenerateBtn1 = new javax.swing.JButton();
        MixCaseOpt_RadBtn = new javax.swing.JRadioButton();
        MixSymbolOpt_RadBtn = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Password Randomizer");

        randomizePassLenghtLabel_v1.setText("Lenght (8-12): ");

        randomizePassLenghtTextField_v1.setText("8");
        randomizePassLenghtTextField_v1.setToolTipText("Add a minimum lenght of 8 and maximum lenght of 12...NUMBERS ONLY");
        randomizePassLenghtTextField_v1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomizePassLenghtTextField_v1ActionPerformed(evt);
            }
        });
        randomizePassLenghtTextField_v1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                randomizePassLenghtTextField_v1KeyTyped(evt);
            }
        });

        randomizeCancelBtn.setText("Cancel");
        randomizeCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomizeCancelBtnActionPerformed(evt);
            }
        });

        randomizeGenerateBtn1.setText("Generate");
        randomizeGenerateBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomizeGenerateBtn1ActionPerformed(evt);
            }
        });

        randomizeOptsButtonGroup.add(MixCaseOpt_RadBtn);
        MixCaseOpt_RadBtn.setSelected(true);
        MixCaseOpt_RadBtn.setText("Alphanumeric + Mix Case");
        MixCaseOpt_RadBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MixCaseOpt_RadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MixCaseOpt_RadBtnActionPerformed(evt);
            }
        });

        randomizeOptsButtonGroup.add(MixSymbolOpt_RadBtn);
        MixSymbolOpt_RadBtn.setText("Alphanumeric + Symbols");
        MixSymbolOpt_RadBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MixSymbolOpt_RadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MixSymbolOpt_RadBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Select an option:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MixCaseOpt_RadBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MixSymbolOpt_RadBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(randomizeGenerateBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(randomizePassLenghtLabel_v1, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(randomizePassLenghtTextField_v1)
                            .addComponent(randomizeCancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(MixCaseOpt_RadBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MixSymbolOpt_RadBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(randomizePassLenghtLabel_v1, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(randomizePassLenghtTextField_v1))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(randomizeGenerateBtn1)
                    .addComponent(randomizeCancelBtn))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void randomizePassLenghtTextField_v1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomizePassLenghtTextField_v1ActionPerformed
        //
    }//GEN-LAST:event_randomizePassLenghtTextField_v1ActionPerformed
    
    private void randomizeCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomizeCancelBtnActionPerformed
        dispose();
    }//GEN-LAST:event_randomizeCancelBtnActionPerformed
    
    Random randomize = new Random();
    String alphaNumMixCase = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
    String alphaNumMixCaseSymbols = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz_-+@&%$#";
 
    //method for generating a mixed-case password according to a user-given char lenght. Note the return is a string (the generated password string)
    public String generatedPasswordMIXCase(int lenght)
        {
            StringBuilder sb = new StringBuilder(lenght);
            for(int i=0; i<lenght; i++)
                sb.append(alphaNumMixCase.charAt(randomize.nextInt(alphaNumMixCase.length())));
            return sb.toString();
        }
    //method for generating a mixed-case-symbol password according to a user-given char-lenght. Note the return is a string (the generated password string)
    public String generatedPasswordMIXCaseSymbol(int lenght)
        {
            StringBuilder sb = new StringBuilder(lenght);
            for(int i=0; i<lenght; i++)
                sb.append(alphaNumMixCaseSymbols.charAt(randomize.nextInt(alphaNumMixCaseSymbols.length())));
            return sb.toString();
        }
     
    
    //method that displays the dialog for random generated passwords, called at click of "GENERATE" button
    public void CreateOutDialog(String psw)                                     //constructor for child dialog - creates child dialog when "Generate" button is clicked, showing the generated password on dialog pop-up
    {                    
        outputdialog = new RandomOuptDialog(this, true); 
        outputdialog.jTextField1.setText(psw);
        outputdialog.jTextField1.selectAll();                                   //when dialog pops-up, text is highlighted so user can copy to clipboard
        outputdialog.setVisible(true);
    }    
    
    //method that generates randomized password when user clicks "Generate" button
    private void randomizeGenerateBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomizeGenerateBtn1ActionPerformed
        try
        {
            int lenghtByUserParsed = Integer.parseInt(randomizePassLenghtTextField_v1.getText()); 
            String passwordGeneratedMix = generatedPasswordMIXCase(lenghtByUserParsed);
            String passwordGeneratedMixSymbol = generatedPasswordMIXCaseSymbol(lenghtByUserParsed);
                                
            if(((lenghtByUserParsed < 8) || (lenghtByUserParsed > 12)))
            {
                JOptionPane.showMessageDialog(null, "Lenght must be 8-12 digits!", "Invalid Lenght!", JOptionPane.ERROR_MESSAGE);
                randomizePassLenghtTextField_v1.setText("8");
                
            }else if(MixCaseOpt_RadBtn.isSelected())
            {
                CreateOutDialog(passwordGeneratedMix);                                                 
                dispose();
            }else if(MixSymbolOpt_RadBtn.isSelected())
            {
                CreateOutDialog(passwordGeneratedMixSymbol);
                dispose();
            }
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "A lenght is required. " + "\n" + "Enter a password lengtht!", "Invalid Lenght" ,JOptionPane.ERROR_MESSAGE);  //if textfield left blank, show error message
            randomizePassLenghtTextField_v1.requestFocusInWindow();
        }
    }//GEN-LAST:event_randomizeGenerateBtn1ActionPerformed

    //handles case when user tries to type non-numers... restrics textfield to number keys only
    private void randomizePassLenghtTextField_v1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_randomizePassLenghtTextField_v1KeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE)))
        {
            getToolkit().beep();
            evt.consume();
        }   
    }//GEN-LAST:event_randomizePassLenghtTextField_v1KeyTyped
    
    
    private void MixCaseOpt_RadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MixCaseOpt_RadBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MixCaseOpt_RadBtnActionPerformed

    private void MixSymbolOpt_RadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MixSymbolOpt_RadBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MixSymbolOpt_RadBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RANDOMIZE_dialogBox_v1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                RANDOMIZE_dialogBox_v1 dialog = new RANDOMIZE_dialogBox_v1(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton MixCaseOpt_RadBtn;
    private javax.swing.JRadioButton MixSymbolOpt_RadBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton randomizeCancelBtn;
    private javax.swing.JButton randomizeGenerateBtn1;
    private javax.swing.ButtonGroup randomizeOptsButtonGroup;
    private javax.swing.JLabel randomizePassLenghtLabel_v1;
    public javax.swing.JTextField randomizePassLenghtTextField_v1;
    // End of variables declaration//GEN-END:variables
}

